services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]

  mongo-express:
    image: mongo-express:1
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"                          # desactiva login de la UI (opcional)
    ports: ["8081:8081"]
    depends_on: [mongo]

  ms-historias:
    build:
      context: .
      target: runner
    env_file: .env
    ports: ["3003:3003"]
    depends_on: [mongo]

volumes:
  mongo_data:
